export const homeObjOne ={
  id: 'about', 
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Preminum Bank',
  heading: 'Unlimited transactions with zero fees', 
  description: 'Get access to our exclusive app that allows you to send unlimited transitions withoug getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/car.svg').default,
  alt: 'car',
  dark: true,
  primary: true,
  darkText: false
};
export const homeObjTwo ={
  id: 'discover', 
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Unlimited Access',
  heading: 'Login to your account at any time', 
  description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or a computer',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../assets/images/savings.svg').default,
  alt: 'piggy bank',
  primary: false,
  dark: false,
  darkText: true,
};
export const homeObjThree ={
  id: 'signup', 
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Join our Team',
  heading: 'Creating an account is extremely easy', 
  description: 'Get everything set up and ready in 10 minutes. All you need to do is add your information and you\'re ready to go ',
  buttonLabel: 'Start Now',
  imgStart: false,
  img: require('../../assets/images/profile.svg').default,
  alt: 'benefites',
  dark: false,
  primary: false,
  darkText: true
};